"""
Reports: daily trade cards (text/markdown) and a backtest report (HTML).

The HTML report is self-contained, so you can open it straight from Finder
with no server running.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import pandas as pd

REPORTS = Path(__file__).resolve().parent.parent / "reports"
REPORTS.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Daily signal report
# ---------------------------------------------------------------------------

def trade_card(sym: str, order, signal, trend: dict) -> str:
    """One trade idea, formatted so you can act on it or reject it in 10 seconds."""
    lines = [
        f"### {sym}",
        "",
        f"| | |",
        f"|---|---|",
        f"| Entry (market on open) | ~${order.entry:,.2f} |",
        f"| Stop | ${order.stop:,.2f} |",
        f"| Target (2R) | ${order.target:,.2f} |",
        f"| Shares | {order.shares} |",
        f"| Position size | ${order.notional:,.2f} ({order.pct_of_equity:.1f}% of account) |",
        f"| If the stop hits, you lose | ${order.dollars_at_risk:,.2f} |",
        f"| Risk per share | ${order.risk_per_share:,.2f} |",
        "",
        f"Setup: closed at ${trend.get('close', 0):,.2f}, "
        f"{trend.get('pct_from_ema', 0):+.2f}% from the 20 EMA "
        f"(${trend.get('ema_pb', 0):,.2f}). "
        f"50 SMA ${trend.get('sma_fast', 0):,.2f} above 200 SMA ${trend.get('sma_slow', 0):,.2f}. "
        f"ATR ${trend.get('atr', 0):,.2f}. {signal.notes}.",
        "",
    ]
    return "\n".join(lines)


def signal_report(cards: List[str], rejected: List[str], equity: float,
                  scanned: int, as_of, cfg) -> str:
    stamp = pd.Timestamp(as_of).date() if as_of is not None else datetime.now().date()
    head = [
        f"# Trade signals for {stamp}",
        "",
        f"Scanned {scanned} symbols. Account equity used for sizing: ${equity:,.2f}. "
        f"Risking {cfg.risk.risk_per_trade * 100:.2f}% per trade.",
        "",
        "These are generated by fixed rules, not by judgment. Rules do not know "
        "about earnings dates, Fed days, or anything that happened in the news. "
        "Read each one before you act on it.",
        "",
    ]
    if not cards:
        head += ["**No setups today.** Nothing on the watchlist met every condition. "
                 "Most days look like this. Taking a trade because you want one is "
                 "how a rule-based system quietly turns into a discretionary one.", ""]
    else:
        head += [f"## {len(cards)} setup(s)", ""] + cards

    if rejected:
        head += ["## Signals that fired but were not sized", ""]
        head += [f"- {r}" for r in rejected]
        head += [""]

    head += [
        "---",
        "",
        "Entries assume a market order at the next session's open. You will not "
        "get the exact price shown. Size off your actual fill, not off this estimate.",
    ]
    return "\n".join(head)


def write_signal_report(text: str, as_of=None) -> Path:
    stamp = pd.Timestamp(as_of).date() if as_of is not None else datetime.now().date()
    path = REPORTS / f"signals_{stamp}.md"
    path.write_text(text)
    return path


# ---------------------------------------------------------------------------
# Backtest HTML report
# ---------------------------------------------------------------------------

_W, _H = 920, 280
_PAD_L, _PAD_R, _PAD_T, _PAD_B = 62, 16, 16, 30


def _scale(vals, lo, hi, out_lo, out_hi):
    span = (hi - lo) or 1.0
    return [out_lo + (v - lo) / span * (out_hi - out_lo) for v in vals]


def _line_chart(dates, values, color_var, fill=False, money=True, invert=False):
    """One series, one axis. Returns (svg, points_json)."""
    n = len(values)
    if n < 2:
        return "<p>Not enough data to plot.</p>", "[]"

    lo, hi = min(values), max(values)
    pad = (hi - lo) * 0.08 or 1.0
    lo, hi = lo - pad, hi + pad
    if invert:
        # Drawdown tops out at zero by definition, so do not pad above it.
        hi = 0.0

    xs = _scale(range(n), 0, n - 1, _PAD_L, _W - _PAD_R)
    ys = _scale(values, lo, hi, _H - _PAD_B, _PAD_T)

    pts = " ".join(f"{x:.2f},{y:.2f}" for x, y in zip(xs, ys))
    base_y = _scale([lo if not invert else 0.0], lo, hi, _H - _PAD_B, _PAD_T)[0]

    area = ""
    if fill:
        area = (f'<polygon points="{xs[0]:.2f},{base_y:.2f} {pts} '
                f'{xs[-1]:.2f},{base_y:.2f}" fill="var({color_var})" opacity="0.14"/>')

    # Gridlines and y ticks: five steps, recessive.
    grid, ticks = [], []
    for k in range(5):
        v = lo + (hi - lo) * k / 4
        y = _scale([v], lo, hi, _H - _PAD_B, _PAD_T)[0]
        grid.append(f'<line x1="{_PAD_L}" y1="{y:.1f}" x2="{_W - _PAD_R}" y2="{y:.1f}" '
                    f'stroke="var(--gridline)" stroke-width="1"/>')
        label = f"${v:,.0f}" if money else f"{v * 100:.0f}%"
        ticks.append(f'<text x="{_PAD_L - 8}" y="{y + 4:.1f}" text-anchor="end" '
                     f'class="tick">{label}</text>')

    # X labels: first, middle, last. The outer two anchor inward so they do
    # not run off the edge of the plot.
    xlab = []
    for k, anchor in ((0, "start"), (n // 2, "middle"), (n - 1, "end")):
        xlab.append(f'<text x="{xs[k]:.1f}" y="{_H - 8}" text-anchor="{anchor}" '
                    f'class="tick">{dates[k]}</text>')

    svg = f"""<svg viewBox="0 0 {_W} {_H}" class="chart" role="img" preserveAspectRatio="none">
  {''.join(grid)}
  {area}
  <polyline points="{pts}" fill="none" stroke="var({color_var})" stroke-width="2"
            stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"/>
  {''.join(ticks)}{''.join(xlab)}
  <line class="crosshair" x1="0" y1="{_PAD_T}" x2="0" y2="{_H - _PAD_B}"
        stroke="var(--muted)" stroke-width="1" stroke-dasharray="3 3" opacity="0"/>
  <circle class="cursor-dot" r="4" fill="var({color_var})" stroke="var(--surface-1)"
          stroke-width="2" opacity="0"/>
</svg>"""

    payload = json.dumps([
        {"x": round(x, 2), "y": round(y, 2), "d": d, "v": v}
        for x, y, d, v in zip(xs, ys, dates, values)
    ])
    return svg, payload


def _tile(label, value, sub="", tone=""):
    cls = f"tile {tone}".strip()
    return (f'<div class="{cls}"><div class="tile-label">{label}</div>'
            f'<div class="tile-value">{value}</div>'
            f'<div class="tile-sub">{sub}</div></div>')


def backtest_html(result, title="Trend pullback backtest") -> str:
    s = result.stats()
    eq = result.equity
    tdf = result.trades_df()

    dates = [d.strftime("%b %Y") for d in eq.index]
    equity_svg, equity_pts = _line_chart(dates, eq["equity"].tolist(), "--series-1")
    dd_svg, dd_pts = _line_chart(dates, (-eq["drawdown"]).tolist(), "--critical",
                                 fill=True, money=False, invert=True)

    ret = s.get("total_return_pct", 0)
    tone_ret = "good" if ret > 0 else "bad"
    exp = s.get("expectancy_R", 0)
    tone_exp = "good" if exp > 0 else "bad"

    tiles = "".join([
        _tile("Total return", f"{ret:+.1f}%",
              f"${s.get('start_equity', 0):,.0f} to ${s.get('end_equity', 0):,.0f}", tone_ret),
        _tile("CAGR", f"{s.get('cagr_pct', 0):+.1f}%", "annualized"),
        _tile("Max drawdown", f"-{s.get('max_drawdown_pct', 0):.1f}%",
              "worst peak-to-trough", "bad"),
        _tile("Expectancy", f"{exp:+.3f}R", "average per trade, in units of risk", tone_exp),
        _tile("Win rate", f"{s.get('win_rate_pct', 0):.0f}%", f"{s.get('trades', 0)} trades"),
        _tile("Profit factor", f"{s.get('profit_factor', 0):.2f}", "gross win / gross loss"),
        _tile("Sharpe", f"{s.get('sharpe', 0):.2f}", "return per unit of volatility"),
        _tile("Time in market", f"{s.get('exposure_pct', 0):.0f}%",
              f"avg hold {s.get('avg_days_held', 0):.0f} days"),
    ])

    exits = s.get("exit_breakdown", {})
    exit_rows = "".join(
        f"<tr><td>{k}</td><td class='num'>{v}</td></tr>" for k, v in
        sorted(exits.items(), key=lambda kv: -kv[1])
    )

    show = tdf.tail(60).iloc[::-1]
    trade_rows = "".join(
        f"<tr><td>{r.symbol}</td><td>{r.entry_date}</td><td>{r.exit_date}</td>"
        f"<td class='num'>{r.shares}</td><td class='num'>${r.entry:,.2f}</td>"
        f"<td class='num'>${r.stop:,.2f}</td><td class='num'>${r.exit:,.2f}</td>"
        f"<td>{r.reason}</td>"
        f"<td class='num {'pos' if r.pnl > 0 else 'neg'}'>${r.pnl:,.2f}</td>"
        f"<td class='num {'pos' if r.R > 0 else 'neg'}'>{r.R:+.2f}R</td></tr>"
        for r in show.itertuples()
    )

    cfg = result.cfg
    params = (f"{cfg.strategy.sma_fast}/{cfg.strategy.sma_slow} SMA trend filter, "
              f"{cfg.strategy.ema_pullback} EMA entry, "
              f"{cfg.strategy.reward_risk:.0f}:1 R/R, "
              f"{cfg.risk.risk_per_trade * 100:.2f}% risk per trade, "
              f"max {cfg.risk.max_open_positions} positions, "
              f"{cfg.costs.slippage_bps:.0f}bp slippage")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    color-scheme: light;
    --surface-1: #fcfcfb; --plane: #f9f9f7;
    --text-primary: #0b0b0b; --text-secondary: #52514e; --muted: #898781;
    --gridline: #e1e0d9; --border: rgba(11,11,11,0.10);
    --series-1: #2a78d6; --critical: #d03b3b; --good: #006300;
  }}
  @media (prefers-color-scheme: dark) {{
    :root:not([data-theme="light"]) {{
      color-scheme: dark;
      --surface-1: #1a1a19; --plane: #0d0d0d;
      --text-primary: #ffffff; --text-secondary: #c3c2b7; --muted: #898781;
      --gridline: #2c2c2a; --border: rgba(255,255,255,0.10);
      --series-1: #3987e5; --critical: #d03b3b; --good: #0ca30c;
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background: var(--plane); color: var(--text-primary);
    font: 14px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif; }}
  .wrap {{ max-width: 1060px; margin: 0 auto; padding: 32px 20px 64px; }}
  h1 {{ font-size: 24px; margin: 0 0 4px; letter-spacing: -0.01em; }}
  h2 {{ font-size: 16px; margin: 34px 0 12px; }}
  .meta {{ color: var(--text-secondary); margin-bottom: 24px; }}
  .tiles {{ display: grid; gap: 10px;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }}
  .tile {{ background: var(--surface-1); border: 1px solid var(--border);
    border-radius: 10px; padding: 14px 16px; }}
  .tile-label {{ color: var(--text-secondary); font-size: 12px; }}
  .tile-value {{ font-size: 26px; font-weight: 600; margin: 4px 0 2px;
    letter-spacing: -0.02em; }}
  .tile-sub {{ color: var(--muted); font-size: 11.5px; }}
  .tile.good .tile-value {{ color: var(--good); }}
  .tile.bad .tile-value {{ color: var(--critical); }}
  .card {{ background: var(--surface-1); border: 1px solid var(--border);
    border-radius: 10px; padding: 16px; position: relative; }}
  .chart {{ width: 100%; height: 280px; display: block; }}
  .tick {{ fill: var(--muted); font-size: 11px;
    font-family: system-ui, sans-serif; font-variant-numeric: tabular-nums; }}
  .tip {{ position: absolute; pointer-events: none; opacity: 0;
    background: var(--surface-1); border: 1px solid var(--border);
    border-radius: 8px; padding: 7px 10px; font-size: 12px;
    box-shadow: 0 4px 14px rgba(0,0,0,.14); transition: opacity .1s;
    white-space: nowrap; z-index: 5; }}
  .tip b {{ font-variant-numeric: tabular-nums; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 12.5px; }}
  th {{ text-align: left; color: var(--text-secondary); font-weight: 500;
    border-bottom: 1px solid var(--border); padding: 7px 8px; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid var(--gridline); }}
  .num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .pos {{ color: var(--good); }} .neg {{ color: var(--critical); }}
  .scroll {{ overflow-x: auto; }}
  .note {{ background: var(--surface-1); border: 1px solid var(--border);
    border-left: 3px solid var(--critical); border-radius: 8px;
    padding: 14px 16px; margin-top: 28px; color: var(--text-secondary); }}
  .two {{ display: grid; gap: 10px; grid-template-columns: 1fr; }}
  @media (min-width: 760px) {{ .two {{ grid-template-columns: 2fr 1fr; }} }}
</style>
</head>
<body>
<div class="wrap">
  <h1>{title}</h1>
  <div class="meta">{params}<br>
    {eq.index[0].date()} to {eq.index[-1].date()} &middot; {s.get('trades', 0)} trades</div>

  <div class="tiles">{tiles}</div>

  <h2>Account equity</h2>
  <div class="card" id="c1">
    {equity_svg}
    <div class="tip" id="t1"></div>
  </div>

  <h2>Drawdown from high water mark</h2>
  <div class="card" id="c2">
    {dd_svg}
    <div class="tip" id="t2"></div>
  </div>

  <div class="two">
    <div>
      <h2>Recent trades (last 60)</h2>
      <div class="card scroll">
        <table>
          <thead><tr><th>Symbol</th><th>In</th><th>Out</th><th class="num">Sh</th>
          <th class="num">Entry</th><th class="num">Stop</th><th class="num">Exit</th>
          <th>Reason</th><th class="num">P&amp;L</th><th class="num">R</th></tr></thead>
          <tbody>{trade_rows}</tbody>
        </table>
      </div>
    </div>
    <div>
      <h2>How trades ended</h2>
      <div class="card">
        <table>
          <thead><tr><th>Reason</th><th class="num">Count</th></tr></thead>
          <tbody>{exit_rows}</tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="note">
    <strong>What this backtest cannot tell you.</strong>
    It is one strategy on one watchlist over one stretch of history, and that
    history contained a specific sequence of market conditions that will not
    repeat. Results improve automatically as you add rules, because every rule
    you add is fitted to the past. Slippage here is a fixed estimate, not your
    actual fills. Nothing here is a prediction, and past performance of a
    backtest is weaker evidence than past performance of real trading, which is
    itself weak evidence. Trade this on paper before you trade it with money.
  </div>
</div>

<script>
(function () {{
  function wire(cardId, tipId, pts) {{
    var card = document.getElementById(cardId);
    var tip = document.getElementById(tipId);
    if (!card || !pts.length) return;
    var svg = card.querySelector('svg');
    var cross = svg.querySelector('.crosshair');
    var dot = svg.querySelector('.cursor-dot');
    var VBW = {_W}, VBH = {_H};

    card.addEventListener('mousemove', function (e) {{
      var r = svg.getBoundingClientRect();
      var vx = (e.clientX - r.left) / r.width * VBW;
      var best = 0, bd = Infinity;
      for (var i = 0; i < pts.length; i++) {{
        var d = Math.abs(pts[i].x - vx);
        if (d < bd) {{ bd = d; best = i; }}
      }}
      var p = pts[best];
      cross.setAttribute('x1', p.x); cross.setAttribute('x2', p.x);
      cross.setAttribute('opacity', '1');
      dot.setAttribute('cx', p.x); dot.setAttribute('cy', p.y);
      dot.setAttribute('opacity', '1');

      var isPct = cardId === 'c2';
      var val = isPct ? (p.v * 100).toFixed(2) + '%'
                      : '$' + p.v.toLocaleString(undefined, {{maximumFractionDigits: 0}});
      tip.innerHTML = p.d + ' &middot; <b>' + val + '</b>';
      tip.style.opacity = '1';
      var px = p.x / VBW * r.width;
      var py = p.y / VBH * r.height;
      tip.style.left = Math.min(Math.max(px - 50, 4), r.width - 150) + 'px';
      tip.style.top = Math.max(py - 42, 4) + 'px';
    }});
    card.addEventListener('mouseleave', function () {{
      tip.style.opacity = '0';
      cross.setAttribute('opacity', '0');
      dot.setAttribute('opacity', '0');
    }});
  }}
  wire('c1', 't1', {equity_pts});
  wire('c2', 't2', {dd_pts});
}})();
</script>
</body>
</html>"""


def write_backtest_html(result, name="backtest.html", title="Trend pullback backtest") -> Path:
    path = REPORTS / name
    path.write_text(backtest_html(result, title))
    return path
